### PR TITLE
Link to the current master build from README

### PR DESCRIPTION
**Pull request by jaseemabid**

### CODE REVIEW

**Comment by fabric8cd** [comment]
snapshot maven-builder image is available for testing.  `docker pull fabric8/maven-builder:SNAPSHOT-PR-26-1`

**Comment by jaseemabid** [comment]
@chmouel No permissions to assign you as a reviewer.

**Comment by chmouel** [comment]
you need to accept the invitation 
image

**Comment by jaseemabid** [comment]
@chmouel I joined the org, but I see the same view even now.

**Comment by jaseemabid** [comment]
@chmouel Can you verify the permissions once more please?

**Comment by chmouel** [comment]
Should be fine, now. No ?

**Comment by jaseemabid** [comment]
@chmouel Yes, thanks.

**Pull request merged**
